-- MySQL Script generated by MySQL Workbench
-- 08/20/14 18:08:21
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Universities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Universities` (
  `UniversityID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UniversityID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Faculties` (
  `FacultyID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Universities_UniversityID` INT NOT NULL,
  PRIMARY KEY (`FacultyID`),
  INDEX `fk_Faculties_Universities_idx` (`Universities_UniversityID` ASC),
  CONSTRAINT `fk_Faculties_Universities`
    FOREIGN KEY (`Universities_UniversityID`)
    REFERENCES `mydb`.`Universities` (`UniversityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departments` (
  `DepartmentID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Faculties_FacultyID` INT NOT NULL,
  PRIMARY KEY (`DepartmentID`),
  INDEX `fk_Departments_Faculties1_idx` (`Faculties_FacultyID` ASC),
  CONSTRAINT `fk_Departments_Faculties1`
    FOREIGN KEY (`Faculties_FacultyID`)
    REFERENCES `mydb`.`Faculties` (`FacultyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Titles` (
  `TitleID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TitleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professors` (
  `ProfessorID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Titles_TitleID` INT NOT NULL,
  `Departments_DepartmentID` INT NOT NULL,
  PRIMARY KEY (`ProfessorID`),
  INDEX `fk_Professors_Titles1_idx` (`Titles_TitleID` ASC),
  INDEX `fk_Professors_Departments1_idx` (`Departments_DepartmentID` ASC),
  CONSTRAINT `fk_Professors_Titles1`
    FOREIGN KEY (`Titles_TitleID`)
    REFERENCES `mydb`.`Titles` (`TitleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professors_Departments1`
    FOREIGN KEY (`Departments_DepartmentID`)
    REFERENCES `mydb`.`Departments` (`DepartmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `CourseID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Departments_DepartmentID` INT NOT NULL,
  `Professors_ProfessorID` INT NOT NULL,
  PRIMARY KEY (`CourseID`),
  INDEX `fk_Courses_Departments1_idx` (`Departments_DepartmentID` ASC),
  INDEX `fk_Courses_Professors1_idx` (`Professors_ProfessorID` ASC),
  CONSTRAINT `fk_Courses_Departments1`
    FOREIGN KEY (`Departments_DepartmentID`)
    REFERENCES `mydb`.`Departments` (`DepartmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_Professors1`
    FOREIGN KEY (`Professors_ProfessorID`)
    REFERENCES `mydb`.`Professors` (`ProfessorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `StudentID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Faculty Number` VARCHAR(10) NOT NULL,
  `Faculties_FacultyID` INT NOT NULL,
  PRIMARY KEY (`StudentID`),
  INDEX `fk_Students_Faculties1_idx` (`Faculties_FacultyID` ASC),
  CONSTRAINT `fk_Students_Faculties1`
    FOREIGN KEY (`Faculties_FacultyID`)
    REFERENCES `mydb`.`Faculties` (`FacultyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students_has_Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Students_has_Courses` (
  `Students_StudentID` INT NOT NULL,
  `Courses_CourseID` INT NOT NULL,
  PRIMARY KEY (`Students_StudentID`, `Courses_CourseID`),
  INDEX `fk_Students_has_Courses_Courses1_idx` (`Courses_CourseID` ASC),
  INDEX `fk_Students_has_Courses_Students1_idx` (`Students_StudentID` ASC),
  CONSTRAINT `fk_Students_has_Courses_Students1`
    FOREIGN KEY (`Students_StudentID`)
    REFERENCES `mydb`.`Students` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_has_Courses_Courses1`
    FOREIGN KEY (`Courses_CourseID`)
    REFERENCES `mydb`.`Courses` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
